import { createFileRoute } from "@tanstack/react-router";

import { Section, SectionHeading } from "@/components/section";
import { Reveal } from "@/components/reveal";
import { CONTACT, breadcrumbJsonLd, pageMeta } from "@/lib/site";

const EFFECTIVE_DATE = "September 4, 2026";

export const Route = createFileRoute("/privacy")({
  head: () => {
    const meta = pageMeta({
      title: "Privacy Policy | Vortex Visual",
      description:
        "Privacy policy for Vortex Visual Operations and the Vortex Visual Backup Google Drive integration.",
      path: "/privacy",
    });

    return {
      ...meta,
      scripts: [
        {
          type: "application/ld+json",
          children: JSON.stringify(
            breadcrumbJsonLd([
              { name: "Home", path: "/" },
              { name: "Privacy Policy", path: "/privacy" },
            ]),
          ),
        },
      ],
    };
  },
  component: PrivacyPage,
});

function PrivacyPage() {
  return (
    <>
      <Section withMotif className="pb-8 md:pb-10">
        <SectionHeading
          as="h1"
          eyebrow="Legal"
          title="Vortex Visual Privacy Policy"
          lead={`Effective date: ${EFFECTIVE_DATE}`}
        />
      </Section>

      <Section className="pt-0">
        <Reveal>
          <article className="pro-panel mx-auto max-w-3xl p-6 text-sm leading-7 text-muted-foreground md:p-8 md:text-base">
            <p>
              Vortex Visual Operations is an internal platform used to manage
              bookings, inventory, staff assignments, and operational records.
            </p>

            <h2 className="mt-8 font-heading text-lg font-bold text-foreground">
              Google Drive Backups
            </h2>
            <p className="mt-3">
              Vortex Visual Backup uses Google Drive only to create, retain,
              and delete encrypted-access backup archives generated by Vortex
              Visual Operations. The integration uses Google&apos;s drive.file
              permission. This means it can manage only backup files created by
              this application; it does not browse or manage unrelated files in
              the connected Google Drive account.
            </p>

            <h2 className="mt-8 font-heading text-lg font-bold text-foreground">
              Information Handling
            </h2>
            <p className="mt-3">
              Backup archives may contain operational database records and
              files required to restore Vortex Visual Operations. They are used
              only for business continuity, recovery, and authorized operational
              support. Vortex Visual does not sell this information or share it
              with third parties for advertising.
            </p>

            <h2 className="mt-8 font-heading text-lg font-bold text-foreground">
              Retention and Security
            </h2>
            <p className="mt-3">
              Backups are retained only for the configured recovery period and
              are accessible only to authorized Vortex Visual personnel and the
              connected Google Drive account.
            </p>

            <h2 className="mt-8 font-heading text-lg font-bold text-foreground">
              Contact
            </h2>
            <p className="mt-3">
              For privacy questions or to request assistance, contact{" "}
              <a
                href={`mailto:${CONTACT.email}`}
                className="font-semibold text-yellow transition-colors hover:text-yellow/80"
              >
                {CONTACT.email}
              </a>
              .
            </p>
          </article>
        </Reveal>
      </Section>
    </>
  );
}
